//! Persisted state: what to steer, what we changed, and how to put it back.
//!
//! Three stores, split by who is allowed to write them:
//!
//! | Store | Path | Writer |
//! |---|---|---|
//! | [`MachineConfig`] | `%ProgramData%\LinkSwitch\config.json` | elevated only |
//! | [`Journal`] | `%ProgramData%\LinkSwitch\state.json` | elevated worker only |
//! | [`UserPrefs`] | `%LOCALAPPDATA%\LinkSwitch\prefs.json` | the widget |
//!
//! The split matters for security: the unelevated widget must not be able to write anything the
//! elevated worker later reads and acts on, or a medium-integrity process could steer the
//! worker's behaviour. The widget only ever asks the worker to run one of a few fixed verbs.
//!
//! # The restore rule
//!
//! LinkSwitch never restores a value it did not capture, and never writes a hardcoded "default"
//! in place of one. Everything it changes is journalled with its **prior** value first, and
//! restore writes that exact value back.
//!
//! This is not fussiness. On the development machine a VPN has applied IPv6 leak protection by
//! unbinding `ms_tcpip6` from every adapter. A restore routine that "helpfully" put things back
//! to Windows defaults would silently switch IPv6 back on and leak the user's real address --
//! damage far worse than the problem it was fixing. Same for metrics: a user who had manually
//! pinned Ethernet to 10 before installing gets 10 back, not "automatic".

use std::path::PathBuf;

use serde::{Deserialize, Serialize};

use crate::net::LuidKey;

/// Bumped whenever a stored struct changes shape. Loading tolerates older versions and anything
/// unparsable falls back to defaults rather than bricking the app.
pub const SCHEMA: u32 = 1;

/// Which link should carry internet traffic.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Mode {
    /// Ethernet wins; Wi-Fi is the standby.
    Ethernet,
    /// Wi-Fi wins. Ethernet stays enabled, link-up and reachable on its own subnet, so a NAS or
    /// printer on the wire keeps working.
    Wifi,
    /// Wi-Fi carries traffic and Ethernet's IP stack is detached entirely: no addresses, no
    /// routes, no DNS servers, no DHCP. The cable stays plugged in and the NIC stays enabled.
    ///
    /// This is zero *IP*, not zero *networking* -- LLDP, LLTD and any VM bridge still reach the
    /// wire. The UI must say so rather than promise silence.
    WifiOnly,
    /// Hand both interfaces back to Windows' automatic metrics.
    Auto,
}

impl Mode {
    pub fn as_str(self) -> &'static str {
        match self {
            Mode::Ethernet => "ethernet",
            Mode::Wifi => "wifi",
            Mode::WifiOnly => "wifi-only",
            Mode::Auto => "auto",
        }
    }

    pub fn parse(s: &str) -> Option<Self> {
        match s.trim().to_ascii_lowercase().as_str() {
            "ethernet" | "eth" | "wired" => Some(Mode::Ethernet),
            "wifi" | "wi-fi" | "wireless" => Some(Mode::Wifi),
            "wifi-only" | "wifionly" | "wi-fi-only" | "only" => Some(Mode::WifiOnly),
            "auto" | "automatic" | "restore" => Some(Mode::Auto),
            _ => None,
        }
    }

    /// The scheduled-task name that applies this mode.
    pub fn task_name(self) -> &'static str {
        match self {
            Mode::Ethernet => "ApplyEthernet",
            Mode::Wifi => "ApplyWifi",
            Mode::WifiOnly => "ApplyWifiOnly",
            Mode::Auto => "ApplyAuto",
        }
    }
}

/// A durable reference to an adapter.
///
/// The identity is the **permanent MAC**, with the adapter GUID as a fast path.
///
/// Two tempting keys are deliberately never matched on:
///
/// * **The LUID.** It looks like a device identity and is not -- it is a reusable slot number.
///   On this machine Ethernet is `0x0006008000000000` and Wi-Fi is `0x0047008000000000`:
///   different `IfType`, but *both* carry `NetLuidIndex == 0x008000`, meaning "first miniport
///   of this type". Replace a NIC and the new one can inherit a byte-identical LUID, at which
///   point a LUID-keyed config silently steers the wrong adapter. It is kept here for
///   diagnostics, and remains the in-process handle passed to the IP Helper calls.
/// * **The current MAC.** Wi-Fi "random hardware addresses" makes it drift;
///   `PermanentPhysicalAddress` does not.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq)]
pub struct AdapterRef {
    /// Diagnostics only -- never used to match. See the type documentation.
    #[serde(default)]
    pub luid: u64,
    /// Adapter GUID, e.g. `{66666666-...}`. Stable across reboots and sleep, but regenerated by
    /// a driver uninstall and reinstall, which is why it is a fast path and not the identity.
    #[serde(default)]
    pub guid: String,
    #[serde(default)]
    pub name: String,
    #[serde(default)]
    pub description: String,
    /// Burned-in MAC, lower-case hex, colon-separated. The real identity.
    #[serde(default, alias = "mac")]
    pub permanent_mac: Option<String>,
}

impl AdapterRef {
    pub fn key(&self) -> LuidKey {
        LuidKey(self.luid)
    }
}

/// Prior state of the WCM "minimize simultaneous connections" policy value.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub struct WcmBackup {
    /// Whether the registry value existed at all before we touched it. Restoring must *delete*
    /// the value when it was originally absent -- writing a 0 back would leave the policy
    /// explicitly disabled rather than at the Windows default.
    pub present: bool,
    pub value: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MachineConfig {
    #[serde(default = "default_schema")]
    pub schema: u32,
    #[serde(default)]
    pub ethernet: Option<AdapterRef>,
    #[serde(default)]
    pub wifi: Option<AdapterRef>,
    /// Metric written to the losing interface. Validated against the allowlist in
    /// [`crate::net::metric`] regardless of what the file says.
    #[serde(default = "default_park")]
    pub park_metric: u32,
    #[serde(default)]
    pub wcm_backup: Option<WcmBackup>,
    /// Last Wi-Fi profile seen connected, used as the fallback target when the worker has to
    /// associate Wi-Fi itself.
    #[serde(default)]
    pub wifi_profile_hint: Option<String>,
}

fn default_schema() -> u32 {
    SCHEMA
}
fn default_park() -> u32 {
    crate::net::metric::PARK_DEFAULT
}

impl Default for MachineConfig {
    fn default() -> Self {
        Self {
            schema: SCHEMA,
            ethernet: None,
            wifi: None,
            park_metric: crate::net::metric::PARK_DEFAULT,
            wcm_backup: None,
            wifi_profile_hint: None,
        }
    }
}

/// One adapter's IP-protocol bindings as they were before we touched them.
///
/// Restoring writes these exact values back. Never `(true, true)`: on this machine a VPN has
/// already unbound `ms_tcpip6` for IPv6 leak protection, and "helpfully" rebinding it would
/// switch IPv6 back on and leak the user's real address.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct BindingBackup {
    /// Adapter GUID -- the handle INetCfg resolves by.
    pub guid: String,
    pub v4: bool,
    pub v6: bool,
}

/// One interface/family metric as it was before we touched it.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub struct MetricBackup {
    pub luid: u64,
    pub family_v6: bool,
    pub metric: u32,
    pub automatic: bool,
}

/// The crash-recovery journal.
///
/// Written **before** any change is made and cleared only after the change is confirmed. If the
/// worker is killed mid-apply -- and it can be, since the task allows hard termination -- this
/// file is what a later run uses to notice a torn state and put the machine back.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Journal {
    #[serde(default = "default_schema")]
    pub schema: u32,
    /// The mode being applied, or the last one successfully applied.
    pub mode: Mode,
    /// True between "about to change something" and "finished". A journal found with this still
    /// set means the previous run died partway through.
    #[serde(default)]
    pub in_flight: bool,
    #[serde(default)]
    pub started_unix: u64,
    #[serde(default)]
    pub finished_unix: Option<u64>,
    /// Prior values for everything touched, so restore is exact rather than "set to default".
    #[serde(default)]
    pub restore: Vec<MetricBackup>,
    /// Prior IP-protocol bindings, for the adapters whose stack we detached.
    #[serde(default)]
    pub bindings: Vec<BindingBackup>,
    #[serde(default)]
    pub last_error: Option<String>,
}

impl Default for Journal {
    fn default() -> Self {
        Self {
            schema: SCHEMA,
            mode: Mode::Auto,
            in_flight: false,
            started_unix: 0,
            finished_unix: None,
            restore: Vec::new(),
            bindings: Vec::new(),
            last_error: None,
        }
    }
}

impl Journal {
    /// A previous run died between changing something and confirming it.
    pub fn is_torn(&self) -> bool {
        self.in_flight && !(self.restore.is_empty() && self.bindings.is_empty())
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserPrefs {
    #[serde(default = "default_schema")]
    pub schema: u32,
    #[serde(default)]
    pub pos: Option<(f32, f32)>,
    #[serde(default)]
    pub start_hidden: bool,
}

impl Default for UserPrefs {
    fn default() -> Self {
        Self {
            schema: SCHEMA,
            pos: None,
            start_hidden: false,
        }
    }
}

// --- paths -------------------------------------------------------------------------------

/// `%ProgramData%\LinkSwitch` -- machine-wide, admin-writable only.
pub fn machine_dir() -> PathBuf {
    let base = std::env::var_os("ProgramData")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from(r"C:\ProgramData"));
    base.join("LinkSwitch")
}

/// `%LOCALAPPDATA%\LinkSwitch` -- per-user, writable by the unelevated widget.
pub fn user_dir() -> PathBuf {
    let base = std::env::var_os("LOCALAPPDATA")
        .map(PathBuf::from)
        .or_else(|| std::env::var_os("APPDATA").map(PathBuf::from))
        .unwrap_or_else(|| PathBuf::from("."));
    base.join("LinkSwitch")
}

pub fn config_path() -> PathBuf {
    machine_dir().join("config.json")
}
pub fn journal_path() -> PathBuf {
    machine_dir().join("state.json")
}
pub fn prefs_path() -> PathBuf {
    user_dir().join("prefs.json")
}
pub fn worker_log_path() -> PathBuf {
    machine_dir().join("logs").join("worker.log")
}
pub fn widget_log_path() -> PathBuf {
    user_dir().join("widget.log")
}

// --- load / save -------------------------------------------------------------------------

fn load_json<T: for<'de> Deserialize<'de> + Default>(path: &std::path::Path) -> T {
    // A missing or corrupt file must degrade to defaults, never abort. This runs in an elevated
    // process during a network change; refusing to start because a JSON file has a stray byte
    // would be the worst possible failure mode.
    match std::fs::read_to_string(path) {
        Ok(s) => serde_json::from_str(&s).unwrap_or_default(),
        Err(_) => T::default(),
    }
}

/// Write atomically: a crash mid-write must not leave a truncated file behind.
fn save_json<T: Serialize>(path: &std::path::Path, value: &T) -> std::io::Result<()> {
    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir)?;
    }
    let tmp = path.with_extension("json.tmp");
    let body = serde_json::to_string_pretty(value)
        .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))?;
    std::fs::write(&tmp, body)?;
    // Windows rename fails if the destination exists, so replace explicitly.
    match std::fs::rename(&tmp, path) {
        Ok(()) => Ok(()),
        Err(_) => {
            let _ = std::fs::remove_file(path);
            std::fs::rename(&tmp, path)
        }
    }
}

pub fn load_machine() -> MachineConfig {
    load_json(&config_path())
}
pub fn save_machine(c: &MachineConfig) -> std::io::Result<()> {
    save_json(&config_path(), c)
}
pub fn load_journal() -> Journal {
    load_json(&journal_path())
}
pub fn save_journal(j: &Journal) -> std::io::Result<()> {
    save_json(&journal_path(), j)
}
pub fn load_prefs() -> UserPrefs {
    load_json(&prefs_path())
}
pub fn save_prefs(p: &UserPrefs) -> std::io::Result<()> {
    save_json(&prefs_path(), p)
}

pub fn now_unix() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

/// Re-resolve a saved adapter against what is present now.
///
/// Tries the LUID, then the permanent MAC, then the friendly name, then the description. A dock
/// being plugged in or a driver being reinstalled changes the LUID, and that is a daily event
/// rather than an exotic edge case, so a LUID-only lookup would tell the user their adapter had
/// disappeared on a regular basis.
pub fn resolve<'a>(
    saved: Option<&AdapterRef>,
    kind: crate::net::adapters::NicKind,
    nics: &'a [crate::net::adapters::Nic],
) -> Option<&'a crate::net::adapters::Nic> {
    let saved = saved?;

    // Only ever consider adapters of the role we saved. Beyond being obviously right, this is a
    // safety property for the MAC match: several interfaces derive their address from a NIC's --
    // on this machine the Bluetooth PAN is one digit from the Wi-Fi radio, and the Wi-Fi Direct
    // pseudo-adapters are derived from it too.
    let of_kind = || nics.iter().filter(|n| n.kind == kind);

    // 1. GUID: an O(1) hit in the overwhelmingly common case.
    if !saved.guid.is_empty() {
        if let Some(n) = of_kind().find(|n| n.adapter_name == saved.guid) {
            return Some(n);
        }
    }

    // 2. Permanent MAC: survives reboots, dock reconnects, driver reinstalls and Wi-Fi MAC
    //    randomisation. This is the identity.
    if let Some(mac) = saved.permanent_mac.as_deref() {
        if let Some(n) = of_kind().find(|n| n.permanent_mac.map(format_mac).as_deref() == Some(mac))
        {
            return Some(n);
        }
    }

    // 3 and 4. Descriptive fallbacks, for a config written before the MAC was recorded or after
    //    hardware was replaced outright. Weak, so they come last.
    if !saved.name.is_empty() {
        if let Some(n) = of_kind().find(|n| n.friendly_name == saved.name) {
            return Some(n);
        }
    }
    if !saved.description.is_empty() {
        if let Some(n) = of_kind().find(|n| n.description == saved.description) {
            return Some(n);
        }
    }
    None
}

pub fn format_mac(mac: [u8; 6]) -> String {
    mac.iter()
        .map(|b| format!("{b:02x}"))
        .collect::<Vec<_>>()
        .join(":")
}

impl From<&crate::net::adapters::Nic> for AdapterRef {
    fn from(n: &crate::net::adapters::Nic) -> Self {
        Self {
            luid: n.luid.0,
            guid: n.adapter_name.clone(),
            name: n.friendly_name.clone(),
            description: n.description.clone(),
            permanent_mac: n.permanent_mac.map(format_mac),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::net::adapters::{Nic, NicKind, Tier};

    fn nic(luid: u64, guid: &str, name: &str, desc: &str, mac: Option<[u8; 6]>) -> Nic {
        Nic {
            luid: LuidKey(luid),
            if_index: 1,
            friendly_name: name.into(),
            description: desc.into(),
            adapter_name: guid.into(),
            if_type: 6,
            kind: NicKind::Ethernet,
            tier: Tier::Hardware,
            oper_up: true,
            media_connected: true,
            tx_speed_bps: Some(1_000_000_000),
            mac: None,
            permanent_mac: mac,
            ipv4: vec![],
            ipv6: vec![],
            gateways: vec![],
        }
    }

    const ETH_MAC: [u8; 6] = [0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0x01];

    #[test]
    fn mode_round_trips_through_strings() {
        for m in [Mode::Ethernet, Mode::Wifi, Mode::Auto] {
            assert_eq!(Mode::parse(m.as_str()), Some(m));
        }
        assert_eq!(Mode::parse("  WiFi "), Some(Mode::Wifi));
        assert_eq!(Mode::parse("wired"), Some(Mode::Ethernet));
        assert_eq!(Mode::parse("nonsense"), None);
    }

    #[test]
    fn resolve_prefers_the_guid() {
        let nics = [
            nic(1, "{aaa}", "Ethernet", "Intel I225-V", None),
            nic(2, "{bbb}", "Ethernet 2", "Intel I225-V", None),
        ];
        let saved = AdapterRef {
            luid: 0,
            guid: "{bbb}".into(),
            name: "Ethernet".into(),
            description: "Intel I225-V".into(),
            permanent_mac: None,
        };
        // The GUID wins even though the name matches the other adapter.
        assert_eq!(
            resolve(Some(&saved), NicKind::Ethernet, &nics).unwrap().luid.0,
            2
        );
    }

    #[test]
    fn resolve_falls_back_to_the_permanent_mac_when_the_guid_changed() {
        // A driver reinstall regenerates the GUID; the burned-in MAC survives it.
        let nics = [nic(999, "{new}", "Ethernet 2", "Intel I225-V", Some(ETH_MAC))];
        let saved = AdapterRef {
            luid: 1,
            guid: "{old}".into(),
            name: "Ethernet".into(),
            description: "Intel I225-V".into(),
            permanent_mac: Some(format_mac(ETH_MAC)),
        };
        assert_eq!(
            resolve(Some(&saved), NicKind::Ethernet, &nics).unwrap().luid.0,
            999
        );
    }

    #[test]
    fn a_matching_luid_alone_is_not_enough_to_bind() {
        // A LUID is a reusable slot number, not a device identity: a replacement NIC can inherit
        // a byte-identical one. Nothing here matches except the LUID, so resolution must fail
        // rather than steer a different adapter.
        let nics = [nic(7, "{other}", "Ethernet 9", "Some Other NIC", Some([1, 2, 3, 4, 5, 6]))];
        let saved = AdapterRef {
            luid: 7,
            guid: "{gone}".into(),
            name: "Ethernet".into(),
            description: "Intel I225-V".into(),
            permanent_mac: Some(format_mac(ETH_MAC)),
        };
        assert!(resolve(Some(&saved), NicKind::Ethernet, &nics).is_none());
    }

    #[test]
    fn resolve_never_crosses_adapter_kinds() {
        // On this machine the Bluetooth PAN MAC is one digit from the Wi-Fi radio's, and the
        // Wi-Fi Direct pseudo-adapters derive theirs from it too. Matching must stay inside the
        // saved role.
        let mut wifi_nic = nic(5, "{w}", "Wi-Fi", "RZ608", Some(ETH_MAC));
        wifi_nic.kind = NicKind::Wifi;
        let nics = [wifi_nic];
        let saved = AdapterRef {
            luid: 0,
            guid: "{w}".into(),
            name: "Wi-Fi".into(),
            description: "RZ608".into(),
            permanent_mac: Some(format_mac(ETH_MAC)),
        };
        assert!(resolve(Some(&saved), NicKind::Ethernet, &nics).is_none());
        assert!(resolve(Some(&saved), NicKind::Wifi, &nics).is_some());
    }

    #[test]
    fn resolve_falls_back_to_name_then_description() {
        let nics = [nic(999, "{new}", "Ethernet", "Intel I225-V", None)];
        let by_name = AdapterRef {
            luid: 1,
            guid: "{old}".into(),
            name: "Ethernet".into(),
            description: "something else".into(),
            permanent_mac: None,
        };
        assert_eq!(
            resolve(Some(&by_name), NicKind::Ethernet, &nics).unwrap().luid.0,
            999
        );

        let by_desc = AdapterRef {
            luid: 1,
            guid: "{old}".into(),
            name: "renamed by the user".into(),
            description: "Intel I225-V".into(),
            permanent_mac: None,
        };
        assert_eq!(
            resolve(Some(&by_desc), NicKind::Ethernet, &nics).unwrap().luid.0,
            999
        );
    }

    #[test]
    fn resolve_gives_up_when_nothing_matches() {
        let mut w = nic(999, "{w}", "Wi-Fi", "RZ608", None);
        w.kind = NicKind::Wifi;
        let nics = [w];
        let saved = AdapterRef {
            luid: 1,
            guid: "{e}".into(),
            name: "Ethernet".into(),
            description: "Intel I225-V".into(),
            permanent_mac: None,
        };
        assert!(resolve(Some(&saved), NicKind::Ethernet, &nics).is_none());
        assert!(resolve(None, NicKind::Ethernet, &nics).is_none());
    }

    #[test]
    fn an_older_config_using_the_mac_field_still_loads() {
        // v0.1.0 wrote the current MAC under "mac"; the field was renamed when it turned out
        // Wi-Fi MAC randomisation makes that value drift.
        let json = r#"{"luid":1,"name":"Ethernet","description":"Intel","mac":"aa:bb:cc:dd:ee:01"}"#;
        let a: AdapterRef = serde_json::from_str(json).unwrap();
        assert_eq!(a.permanent_mac.as_deref(), Some("aa:bb:cc:dd:ee:01"));
    }

    #[test]
    fn a_journal_left_in_flight_is_torn() {
        let mut j = Journal::default();
        assert!(!j.is_torn());
        j.in_flight = true;
        // In-flight with nothing recorded yet means nothing was changed.
        assert!(!j.is_torn());
        j.restore.push(MetricBackup {
            luid: 1,
            family_v6: false,
            metric: 5,
            automatic: true,
        });
        assert!(j.is_torn());
        j.in_flight = false;
        assert!(!j.is_torn());
    }

    #[test]
    fn unknown_fields_and_missing_fields_survive_a_round_trip() {
        // Forward compatibility: a config written by a later version must not brick this one.
        let json = r#"{"schema":99,"park_metric":1234,"future_field":true}"#;
        let c: MachineConfig = serde_json::from_str(json).unwrap();
        assert_eq!(c.park_metric, 1234);
        assert!(c.ethernet.is_none());

        // And a totally empty object gets sane defaults.
        let c: MachineConfig = serde_json::from_str("{}").unwrap();
        assert_eq!(c.park_metric, crate::net::metric::PARK_DEFAULT);
    }

    #[test]
    fn corrupt_config_degrades_to_defaults_rather_than_failing() {
        let c: MachineConfig = serde_json::from_str("not json at all").unwrap_or_default();
        assert_eq!(c.schema, SCHEMA);
    }

    #[test]
    fn mac_formatting_is_stable_lowercase_hex() {
        assert_eq!(
            format_mac([0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0x02]),
            "aa:bb:cc:dd:ee:02"
        );
        assert_eq!(format_mac([0, 0, 0, 0, 0, 0]), "00:00:00:00:00:00");
    }
}
